In [1]:
import numpy as np

In [2]:
# input ukuran matriks dari user
m = int(input("masukkan jumlah persamaan (m): "))
n = int(input("masukkan jumlah variabel (n): "))

# generate matriks koefisien a dan vektor b secara acak rentang -50 sampai 50
a = np.random.uniform(-50.0, 50.0, (m, n))
b = np.random.uniform(-50.0, 50.0, m)

# tampilkan spl yang terbentuk
print("\nsistem persamaan linear (spl):")
for i in range(m):
    persamaan = ""
    for j in range(n):
        if j == 0:
            persamaan += "%.4f*x%d" % (a[i, j], j+1)
        else:
            if a[i, j] >= 0:
                persamaan += " + %.4f*x%d" % (a[i, j], j+1)
            else:
                persamaan += " - %.4f*x%d" % (abs(a[i, j]), j+1)
    persamaan += " = %.4f" % b[i]
    print(persamaan)

# tampilkan matriks augmentasi [a | b]
print("\nmatriks augmentasi [a | b]:")
print(np.column_stack((a, b)))


sistem persamaan linear (spl):
-6.0050*x1 + 2.9734*x2 - 24.7925*x3 = -4.9070
-49.6541*x1 + 25.1185*x2 + 4.0669*x3 = -15.7444
40.3175*x1 - 12.1094*x2 + 31.0451*x3 = -45.7187

matriks augmentasi [a | b]:
[[ -6.00495715   2.97339304 -24.79249206  -4.90703526]
 [-49.65414829  25.11851707   4.06689719 -15.74443141]
 [ 40.31754035 -12.10936387  31.04506274 -45.71868166]]


In [3]:
# proses eliminasi gauss naif
# loop tiap kolom
iterasi = 0
for k in range(n):
    # cek pivot (diagonal utama matriks) apakah 0? 
    if a[k,k] == 0:
        # kalau iya, coba tukar baris
        for i in range(k, len(b)):      # cek baris di bawah
            if a[i, k] != 0:            # cari yang tidak nol         
                a[[k, i]] = a[[i, k]]   # tukar baris k (yang nol) dgn baris i (yang tdk nol) utk matriks a
                b[[k, i]] = b[[i, k]]   # tukar baris k (yang nol) dgn baris i (yang tdk nol) utk matriks b
                break

    # ambil pivot    
    pivot = a [k, k]

    # jika setelah swap pivot masih 0 berarti matriks tidak bisa diselesaikan
    if pivot == 0:  
        raise ValueError("Sistem tidak memiliki solusi unik atau tak terdefinisi.")
    
    # ubah pivot jadi 1
    a[k,:] /= pivot
    b[k] /= pivot
    
    # buat semua elemen di bawah pivot jadi 0
    for i in range(k+1, n):
        factor = a[i, k] 
        a[i, k:] -= factor * a[k, k:]
        b[i] -= factor * b[k]

    iterasi += 1

    print("\niterasi ke-%d (setelah eliminasi kolom %d):" % (iterasi, k+1))
    print(np.column_stack((a, b)))

# substitusi mundur untuk mendapatkan hasil (cari nilai x dari bawah ke atas)
print("\nmatriks a")
print(a)
print("\nmatriks b")
print(b)

# buat array solusi 
x = np.zeros(n)

# mulai dari variabel terakhir (z)
x[-1] = b[-1] / a[-1, -1]

# loop dari bawah ke atas
for i in range(n-2, -1, -1):
    # hitung jumlah a[i][j] * x[j] untuk j di kanan diagonal
    sum_val = b[i] - np.dot(a[i, i+1:], x[i+1:])
    # cari nilai x[i]
    x[i] = sum_val / a[i, i]

print("\nSolusi:")
for i in range(len(x)):
    print("x%d = %.4f" % (i+1, x[i]))


iterasi ke-1 (setelah eliminasi kolom 1):
[[   1.           -0.49515641    4.12867094    0.81716408]
 [   0.            0.53194712  209.07253622   24.83115485]
 [   0.            7.85412478 -135.41279441  -78.66472731]]

iterasi ke-2 (setelah eliminasi kolom 2):
[[ 1.00000000e+00 -4.95156413e-01  4.12867094e+00  8.17164077e-01]
 [ 0.00000000e+00  1.00000000e+00  3.93032556e+02  4.66797430e+01]
 [ 0.00000000e+00  0.00000000e+00 -3.22233954e+03 -4.45293254e+02]]

iterasi ke-3 (setelah eliminasi kolom 3):
[[ 1.00000000e+00 -4.95156413e-01  4.12867094e+00  8.17164077e-01]
 [ 0.00000000e+00  1.00000000e+00  3.93032556e+02  4.66797430e+01]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00  1.38189427e-01]]

matriks a
[[  1.          -0.49515641   4.12867094]
 [  0.           1.         393.03255636]
 [ -0.          -0.           1.        ]]

matriks b
[ 0.81716408 46.67974305  0.13818943]

Solusi:
x1 = -3.5330
x2 = -7.6332
x3 = 0.1382
