In [11]:
import numpy as np

In [12]:
# input ukuran matriks dari user
m = int(input("masukkan jumlah persamaan (m): "))
n = int(input("masukkan jumlah variabel (n): "))

# generate matriks koefisien a dan vektor b secara acak rentang -50 sampai 50
a = np.random.uniform(-50.0, 50.0, (m, n))
b = np.random.uniform(-50.0, 50.0, m)

# tampilkan spl yang terbentuk
print("\nsistem persamaan linear (spl):")
for i in range(m):
    persamaan = ""
    for j in range(n):
        if j == 0:
            persamaan += "%.4f*x%d" % (a[i, j], j+1)
        else:
            if a[i, j] >= 0:
                persamaan += " + %.4f*x%d" % (a[i, j], j+1)
            else:
                persamaan += " - %.4f*x%d" % (abs(a[i, j]), j+1)
    persamaan += " = %.4f" % b[i]
    print(persamaan)

# tampilkan matriks augmentasi [a | b]
print("\nmatriks augmentasi [a | b]:")
print(np.column_stack((a, b)))


sistem persamaan linear (spl):
6.2329*x1 - 28.5834*x2 - 38.1942*x3 = -1.2369
-42.1395*x1 + 42.3383*x2 + 27.2309*x3 = 28.2075
13.0519*x1 - 7.1760*x2 - 17.3468*x3 = 30.0150

matriks augmentasi [a | b]:
[[  6.23291396 -28.58335606 -38.19421431  -1.23692553]
 [-42.13951825  42.33831469  27.23093912  28.20745122]
 [ 13.05185049  -7.17601817 -17.34680616  30.01503326]]


In [ ]:
# proses eliminasi gauss jordan
# loop kolom (loop pivot)
iterasi = 0
for k in range(n):
    # swap kalau pivot 0
    if a[k, k] == 0:
        for i in range(k, m):
            if a[i, k] != 0:
                a[[k, i]] = a[[i, k]]
                b[[k, i]] = b[[i, k]]
                break

    # ambil pivot
    pivot = a[k, k]

    # jika setelah swap pivot masih 0 berarti matriks tidak bisa diselesaikan
    if pivot == 0:
        raise ValueError("sistem tidak memiliki solusi unik atau tak terdefinisi.")

    # ubah pivot jadi 1
    a[k, :] /= pivot
    b[k] /= pivot

    # loop semua baris (0 sampai m-1) untuk eliminasi kolom pivot
    for i in range(m):
        # skip baris pivot atau kalau sudah 0 tidak perlu dieliminasi
        if (i == k or a[i, k] == 0):
            continue
        # nilai pengali untuk menghilangkan elemen di kolom pivot
        factor = a[i, k]
        # loop setiap kolom dari kolom pivot sampai akhir
        for j in range(k, n):
            # operasi eliminasi gauss-jordan
            a[i, j] -= factor * a[k, j]     # matriks a
        b[i] -= factor * b[k]               # vektor b

    iterasi += 1
    print("\niterasi ke-%d (setelah eliminasi kolom %d):" % (iterasi, k+1))
    print(np.column_stack((a, b)))


iterasi ke-1 (setelah eliminasi kolom 1):
[[ 1.00000000e+00 -4.58587368e+00 -6.12782633e+00 -1.98450602e-01]
 [ 0.00000000e+00 -1.50908193e+02 -2.30992711e+02  1.98448385e+01]
 [ 0.00000000e+00  5.26781194e+01  6.26326670e+01  3.26051808e+01]]

iterasi ke-2 (setelah eliminasi kolom 2):
[[  1.           0.           0.89169574  -0.80150548]
 [ -0.           1.           1.5306837   -0.13150272]
 [  0.           0.         -18.00087162  39.53249705]]

iterasi ke-3 (setelah eliminasi kolom 3):
[[ 1.          0.          0.          1.15678632]
 [-0.          1.          0.          3.23009832]
 [-0.         -0.          1.         -2.19614349]]


In [15]:
# tampilkan matriks akhir setelah eliminasi gauss jordan (bentuk identitas)
print("matriks augmentasi setelah eliminasi gauss jordan (bentuk identitas):")
print(np.column_stack((a, b)))

# solusi akhir langsung dari vektor b
print("\nsolusi akhir:")
for i in range(n):
    print("x%d = %.4f" % (i+1, b[i]))

matriks augmentasi setelah eliminasi gauss jordan (bentuk identitas):
[[ 1.          0.          0.          1.15678632]
 [-0.          1.          0.          3.23009832]
 [-0.         -0.          1.         -2.19614349]]

solusi akhir:
x1 = 1.1568
x2 = 3.2301
x3 = -2.1961
