In [1]:
import numpy as np

In [ ]:
# matriks koefisien
a = np.array([[0, 2, 3],
             [1, 4, 6],
             [2, 5, 7]], dtype=float)

# vektor hasil
b = np.array([5,9,12], dtype=float)
# jumlah variabel
n = len(b)

# gabung matriks a dan b
print("Augmentasi Matriks: \n", np.column_stack((a, b)))

# loop kolom
for k in range(n):
    # swap kalau pivot 0
    if a[k,k] == 0:
        for i in range(k, len(b)):
            if a[i, k] != 0:
                a[[k, i]] = a[[i, k]]
                b[[k, i]] = b[[i, k]]
                break
    # ambil pivot
    pivot = a [k, k]
    # kalau ttp 0 gbs dihitung
    if pivot == 0:  
        raise ValueError("Sistem tidak memiliki solusi unik atau tak terdefinisi.")
    # ubah pivot jd 1
    a[k, :] /= pivot
    b[k] /= pivot

    # loop semua baris (0 sampai n-1)
    for i in range(n):
        # skip baris pivot or kalau sudah 0 tdk perlu dieliminasi
        if (i == k or a[i, k] == 0): 
            continue
        # nilai pengali untuk menghilangkan elemen di kolom pivot
        factor = a[i, k]
        # loop setiap kolom, dari kolom pivot sampai akhir
        for j in range(k, n):
            # operasi eliminasi Gauss-Jordan
            a[i, j] -=  factor * a[k, j]        # matriks a
        b[i] -= factor * b[k]                   # vektor b

# tampilkan hasil matriks setelah eliminasi Gauss-Jordan
print("\n Gauss Jordan: \n", np.column_stack((a,b)))
print()

# tampilkan nilai vektor hasil b satu per satu
for i in range(len(b)):
    print("b%d = %.4f" % (i+1, b[i]))

Augmentasi Matriks: 
 [[ 0.  2.  3.  5.]
 [ 1.  4.  6.  9.]
 [ 2.  5.  7. 12.]]

 Gauss Jordan: 
 [[ 1.  0.  0. -1.]
 [ 0.  1.  0.  7.]
 [-0. -0.  1. -3.]]

b1 = -1.0000
b2 = 7.0000
b3 = -3.0000


### CATATAN
### Ubah elemen di bawah pivot jadi 0

Misalnya kita ada matriks ini
$$
\left[
\begin{array}{ccc|c}
1 & 4 & 6 & 9 \\
0 & 2 & 3 & 5 \\
2 & 5 & 7 & 12
\end{array}
\right]
$$

pertama mulai dari
loop kolom

``` python
    # gauss jordan
    for i in range(n):
        if (i == k or a[i, k] == 0): 
            continue
        factor = a[i, k]
        for j in range(k, n):
            a[i, j] -=  factor * a[k, j]
        b[i] -= factor * b[k]
```

`k` = 0

`n` = 3

``` python
    for i in range(n):
```

```
    for i in range(3):
```

- `i` = 0 → skip karena pivot sendiri

- `i` = 1 → `a[1,0] = 0` → skip karena sudah 0

- `i` = 2 → `a[2,0] = 2` → ini yang aktif

jadi `continue`

`factor = a[2,0] = 2`

---

``` python
        for j in range(k, n):
            a[i, j] = a[i, j] - factor * a[k, j]
```

``` 
        for j in range(0, 3):
            a[2,j] = a[2,j] - factor * a[0,j]
```

- `j` = 0 → `a[2,0] = a[2,0] - factor * a[0,0]`

- `j` = 1 → `a[2,1] = a[2,1] - factor * a[0,1]`

- `j` = 2 → `a[2,2] = a[2,2] - factor * a[0,2]`

---

Notes:

**Baris 0 (i = 0)**

Ini baris pivot

- `a[0,0] = 1`   → baris 0 kolom 0 (pivot kolom 0)

- `a[0,1] = 4`   → baris 0 kolom 1

- `a[0,2] = 6`   → baris 0 kolom 2

**Baris 2 (i = 2)**

Ini baris yang mau dijadiin 0

- `a[2,0] = 2`   → baris 2 kolom 0

- `a[2,1] = 5`   → baris 2 kolom 1

- `a[2,2] = 7`   → baris 2 kolom 2
---

Maka

- `j` = 0 → `2 = 2 - 2 * 1` → `2 = 0`

- `j` = 1 → `5 = 5 - 2 * 4` → `1 = -3`

- `j` = 2 → `7 = 7 - 2 * 6` → `7 = -5`

---
``` python
    b[i] -= factor * b[k]
```

```
b[2] = b[2] - 2 × b[0]
     = 12 - 2 × 9
     = 12 - 18
     = -6
```