In [1]:
!pip install numpy

^C


   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 563.7 kB/s eta 0:00:22
   - -------------------------------------- 0.5/12.4 MB 563.7 kB/s eta 0:00:22
   - -------------------------------------- 0.5/12.4 MB 563.7 kB/s eta 0:00:22
   - -------------------------------------- 0.5/12.4 MB 563.7 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/12.4 MB 478.9 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/12.4 MB 478.9 kB/s eta 0:00:25
   -- ------------------------------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a = np.array([[1,2,3],
            [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
print(a.shape)

(2, 3)


In [7]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [9]:
x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [12]:
x = np.ones([2,3])
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
z = np.full((3,3), 2)
print(z)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [16]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [18]:
a = np.arange(10, 20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [19]:
a = np.arange(10)
print(a)

print(a[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [36]:
a = np.array([[1,2,3,4],
            [3,4,5,6],
            [4,5,6,4]])
print(a)

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 4]]


In [37]:
a[1]

array([3, 4, 5, 6])

In [38]:
a[:]

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [4, 5, 6, 4]])

In [39]:
print("kolom 2 : ")
print(a[:, 1])

kolom 2 : 
[2 4 5]


In [40]:
print("baris 2 : ")
print(a[1, :])

baris 2 : 
[3 4 5 6]


In [41]:
print("kolom 2 - akhir")
print(a[:, 1:])

kolom 2 - akhir
[[2 3 4]
 [4 5 6]
 [5 6 4]]


In [42]:
print("baris 2 dan 3: ")
print(a[1:, :])

baris 2 dan 3: 
[[3 4 5 6]
 [4 5 6 4]]


In [132]:
print("kolom 2 - akhir")
print(a[0:2, 2:4])

kolom 2 - akhir
[]


In [58]:
print("kolom 2 - akhir")
print(a [:2, :2])

kolom 2 - akhir
[[1 2]
 [3 4]]


In [59]:
a = np.array([[1,2],
            [3,4],
            [5,6]])
print(a)

bool_idx = a > 2
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [71]:
print(a[a>2])

[3 4 5 6]


In [72]:
x = np.array([[1,2],[3,4]], dtype = float)
y = np.array([[5,6],[7,8]], dtype = float)

print(x)
print(y)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [74]:
print("penjumlahan")
print(x+y)
print(np.add(x,y))

penjumlahan
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [75]:
print("pengurangan")
print(x-y)
print(np.subtract(x,y))

pengurangan
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [76]:
print("pengalian")
print(x*y)
print(np.multiply(x,y))

pengalian
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [78]:
print("pembagian")
print(x/y)
print(np.divide(x,y))

pembagian
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [96]:
print(x)
print("akar")
print(np.sqrt(x))

[[1. 2.]
 [3. 4.]]
akar
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [97]:
print(np.exp(1))
print(np.exp(2))

2.718281828459045
7.38905609893065


In [ ]:
print(np.sin(30))
print(np.cos(0))
print(np.tan(45))

-0.9880316240928618
1.0
1.6197751905438615


In [108]:
print(np.sin(np.pi/6))
print(np.cos(0))
print(np.tan(np.pi/4))

0.49999999999999994
1.0
0.9999999999999999
